spring.application.name=backend

# Aiven MySQL ?? ??
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Timezone
spring.jackson.time-zone=Asia/Seoul

# Swagger ??
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ?? ??
server.port=8080

# JWT ??
jwt.secret=checkmate-checkmate-checkmate-checkmate-secret-key
jwt.expiration=86400000

# Security Debug
logging.level.org.springframework.security=DEBUG